default: &default
  adapter:  mysql2
  encoding: utf8
  username: spotev
  password: spotev17
  host: spotev.cdckrf7rme4v.us-west-2.rds.amazonaws.com
  port: 3306

development:
  <<: *default
  database: spotev

test:
  <<: *default
  database: spotev
